$(document).ready(function(){
$('#bRemove10').click(function() {
    $('#form').css('visibility','visible');
	$('#tblList').css('visibility','hidden');
		$('#tblList2').css('visibility','hidden');
	$('#bAdd').css('visibility','visible');
	$('#bUpdate').css('visibility','visible');
	$('#title').css('visibility','visible');
	$('#alarm').css('visibility','visible');
	$('#canvas').css('visibility','visible');
	$('#edit').css('visibility','hidden');
	$('#edit1').css('visibility','hidden');
		$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
		$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#chose').css('visibility','hidden');
})
$('#bRemove20').click(function() {
    $('#form1').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#tblList').css('visibility','hidden');
		$('#tblList2').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','visible');
	$('#time').css('visibility','visible');
	$('#start').css('visibility','visible');
	$('#cancel').css('visibility','visible');
	$('#canvas').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#edit1').css('visibility','hidden');
		$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
	$('#chose').css('visibility','hidden');
})
$('#cancel').click(function() {
    $('#form1').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#tblList2').css('visibility','visible');
		$('#tblList').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#chose').css('visibility','visible');
	$('#time').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#edit1').css('visibility','hidden');
		$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
})
$('#option1').click(function() {
    $('#form1').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#tblList').css('visibility','visible');
	$('#tblList2').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#edit1').css('visibility','hidden');
	$('#chose').css('visibility','visible');
		$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
})
$('#option2').click(function() {
    $('#form1').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#tblList').css('visibility','hidden');
	$('#tblList2').css('visibility','visible');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#chose').css('visibility','visible');
	$('#time').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#edit1').css('visibility','hidden');
		$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
})
$('#start').click(function() {
List1();
    $('#form1').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#tblList').css('visibility','hidden');
	$('#tblList2').css('visibility','visible');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#chose').css('visibility','visible');
	$('#time').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#edit1').css('visibility','hidden');
		$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
})
$('#edit').click(function() {
    $('#form').css('visibility','visible');
		$('#tblList2').css('visibility','hidden');
	$('#tblList').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#bAdd3').css('visibility','visible');
	$('#bUpdate3').css('visibility','visible');
	$('#title').css('visibility','visible');
		$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#chose').css('visibility','hidden');
})
$('#bUpdate').click(function() {
		List();
	$('#tblList').css('visibility','visible');
		$('#tblList2').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#alarm').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	
	$('#chose').css('visibility','visible');
})

$('#bUpdate3').click(function() {
   List();
	$('#tblList').css('visibility','visible');
		$('#tblList2').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#edit').css('visibility','visible');
	$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
	$('#alarm').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
$('#chose').css('visibility','visible');
})
$('#bAdd').click(function() {
   List();
	$('#tblList').css('visibility','visible');
		$('#tblList2').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#edit').css('visibility','visible');
	$('#edit1').css('visibility','visible');
	$('#alarm').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#chose').css('visibility','visible');
})
$('#bAdd3').click(function() {
   List();
	$('#tblList').css('visibility','visible');
		$('#tblList2').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
	$('#edit').css('visibility','visible');
	$('#edit1').css('visibility','visible');
	$('#alarm').css('visibility','hidden');
	$('#canvas').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#chose').css('visibility','visible');
})
$('#total').click(function() {
   List();
	$('#tblList').css('visibility','visible');
		$('#tblList2').css('visibility','hidden');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#total').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#chose').css('visibility','hidden');
})
$('#bRemove2').click(function() {
   
	$('#tblList').css('visibility','hidden');
	$('#tblList2').css('visibility','hidden');
	$('#total').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#cr1').css('visibility','hidden');
	$('#time').css('visibility','hidden');
	$('#form1').css('visibility','hidden');
	$('#start').css('visibility','hidden');
	$('#cancel').css('visibility','hidden');
	$('#chose').css('visibility','hidden');
})

});