$(document).ready(function(){

$('#bRemove').click(function() {
    $('#form1').css('visibility','visible');
	 $('#form2').css('visibility','hidden');
	 $('#day').css('visibility','hidden');
	$('#day1').css('visibility','hidden');
	$('#day2').css('visibility','hidden');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	$('#work1').css('visibility','hidden');
	$('#accordion12').css('visibility','hidden')
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#rec').css('visibility','hidden')
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')	
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#rec1').css('visibility','hidden')
		$('#accordion30').css('visibility','hidden')
})
$('#bRemove2').click(function() {
    $('#form2').css('visibility','visible');
		$('#title').css('visibility','hidden');
    $('#form1').css('visibility','hidden');
	$('#qu').css('visibility','hidden');
	$('#work1').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
$('#rec1').css('visibility','hidden')
		$('#accordion30').css('visibility','hidden')
	
})
$('#body').click(function() {
    $('#form2').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#work1').css('visibility','visible');
	$('#day').css('visibility','visible');
		$('#rec').css('visibility','hidden')
		$('#day1').css('visibility','hidden');
	$('#day2').css('visibility','hidden');
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden');
	$('#rec1').css('visibility','hidden')
		$('#accordion30').css('visibility','hidden')
	
})
$('#without').click(function() {
    $('#form2').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#work1').css('visibility','visible');
	$('#day').css('visibility','hidden');
	$('#day1').css('visibility','visible');
$('#rec1').css('visibility','hidden')
		$('#accordion30').css('visibility','hidden')
	$('#rec').css('visibility','hidden')
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden');
	
})
$('#fat').click(function() {
    $('#form2').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#work1').css('visibility','visible');
	$('#day').css('visibility','hidden');
	$('#day1').css('visibility','hidden');
	$('#day2').css('visibility','visible');
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	$('#rec').css('visibility','hidden')
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#accordion12').css('visibility','hidden')
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#rec').css('visibility','hidden');
	
})
$('#option1').click(function(){
	$('#rec').css('visibility','hidden')
	$('#accordion30').css('visibility','visible');
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec1').css('visibility','visible');
	})
$('#option2').click(function(){
$('#rec').css('visibility','hidden')
		$('#accordion30').css('visibility','visible')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec1').css('visibility','visible');})
$('#option3').click(function(){
$('#rec').css('visibility','hidden')
$('#rec1').css('visibility','hidden')
	$('#accordion20').css('visibility','hidden')
		$('#accordion30').css('visibility','visible');
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden');})
$('#option4').click(function(){
$('#rec').css('visibility','hidden')
		$('#accordion30').css('visibility','visible');
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec1').css('visibility','visible');})
$('#option5').click(function(){
$('#rec').css('visibility','hidden')
		$('#accordion30').css('visibility','visible');
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec1').css('visibility','visible');})

$('#option6').click(function(){
	$('#rec').css('visibility','hidden')
	$('#accordion30').css('visibility','visible');
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec1').css('visibility','visible');})
	
$('#option7').click(function(){
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion30').css('visibility','hidden');

	$('#rec1').css('visibility','hidden')
	$('#rec').css('visibility','visible');})

$('#options1').click(function(){
	
	$('#accordion20').css('visibility','visible');
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec').css('visibility','hidden');
	})
$('#options2').click(function(){
	$('#accordion20').css('visibility','hidden')
	$('#rec').css('visibility','visible')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden');})
$('#options3').click(function(){
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','visible')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec').css('visibility','hidden');})
$('#options4').click(function(){
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec').css('visibility','visible');})
$('#options5').click(function(){
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','visible')
	$('#accordion23').css('visibility','hidden')
	$('#rec').css('visibility','hidden');})

$('#options6').click(function(){
$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','hidden')
	$('#rec').css('visibility','visible');})
	
$('#options7').click(function(){
	$('#accordion20').css('visibility','hidden')
	$('#accordion21').css('visibility','hidden')
	$('#accordion22').css('visibility','hidden')
	$('#accordion23').css('visibility','visible')
	$('#rec').css('visibility','hidden');})

$('#optionsRadios1').click(function(){
	$('#accordion11').css('visibility','hidden')
		$('#rec').css('visibility','hidden')
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#accordion12').css('visibility','hidden')
	
	$('#accordion10').css('visibility','visible');
	})
$('#optionsRadios2').click(function(){
	$('#rec').css('visibility','hidden')
		$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#accordion12').css('visibility','hidden')
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','visible');})
$('#optionsRadios3').click(function(){
$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#accordion12').css('visibility','hidden')
	$('#accordion10').css('visibility','hidden')
	
	$('#rec').css('visibility','visible');})
$('#optionsRadios4').click(function(){
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	$('#rec').css('visibility','hidden')
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#accordion12').css('visibility','visible');})
$('#optionsRadios5').click(function(){
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	$('#rec').css('visibility','hidden')
	$('#accordion12').css('visibility','hidden')
	$('#accordion13').css('visibility','visible')
	$('#accordion14').css('visibility','hidden');})

$('#optionsRadios6').click(function(){
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	$('#rec').css('visibility','hidden')
	$('#accordion12').css('visibility','hidden')
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','visible');})
	
$('#optionsRadios7').click(function(){
	$('#accordion10').css('visibility','hidden')
	$('#accordion11').css('visibility','hidden')
	
	$('#accordion12').css('visibility','hidden')
	$('#accordion13').css('visibility','hidden')
	$('#accordion14').css('visibility','hidden')
	$('#rec').css('visibility','visible');})
		
$('#back').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','visible');
	$('#title2').css('visibility','hidden');
		
		$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	})
$('#biceps').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','visible');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','visible');
	$('#accordion').css('visibility','hidden');
		$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	})
$('#triceps').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','visible');
	$('#accordion2').css('visibility','visible');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	})
$('#chest').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','visible');
	$('#accordion3').css('visibility','visible');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	
	})
$('#shoulders').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','visible');
	$('#accordion4').css('visibility','visible');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	})
$('#abs').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','visible');
	$('#accordion5').css('visibility','visible');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	})
$('#legs').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','visible');
	$('#accordion6').css('visibility','visible');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	})
$('#cardio').click(function() {
      $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title9').css('visibility','hidden');
	$('#accordion8').css('visibility','hidden');
	$('#title8').css('visibility','visible');
	$('#accordion7').css('visibility','visible');
	})
$('#forearms').click(function() {
    $('#form1').css('visibility','visible');
	$('#qu').css('visibility','hidden');
	$('#title').css('visibility','visible');
	$('#accordion1').css('visibility','hidden');
	$('#title1').css('visibility','hidden');
	$('#title2').css('visibility','hidden');
	$('#accordion').css('visibility','hidden');
	$('#title3').css('visibility','hidden');
	$('#accordion2').css('visibility','hidden');
	$('#title4').css('visibility','hidden');
	$('#accordion3').css('visibility','hidden');
	$('#title5').css('visibility','hidden');
	$('#accordion4').css('visibility','hidden');
	$('#title6').css('visibility','hidden');
	$('#accordion5').css('visibility','hidden');
	$('#title7').css('visibility','hidden');
	$('#accordion6').css('visibility','hidden');
	$('#title8').css('visibility','hidden');
	$('#accordion7').css('visibility','hidden');
	$('#title9').css('visibility','visible');
	$('#accordion8').css('visibility','visible');
	})
$('#edit').click(function() {
    $('#form').css('visibility','visible');
	$('#tblList').css('visibility','hidden');
	$('#edit').css('visibility','hidden');
	$('#bAdd3').css('visibility','visible');
	$('#bUpdate3').css('visibility','visible');
	$('#title').css('visibility','visible');
	
})
$('#bUpdate').click(function() {
   List();
	$('#tblList').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
})
$('#bUpdate3').click(function() {
   List();
	$('#tblList').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#edit').css('visibility','visible');
	$('#bAdd3').css('visibility','hidden');
	$('#bUpdate3').css('visibility','hidden');
})
$('#bAdd').click(function() {
   List();
	$('#tblList').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#edit').css('visibility','visible');
})
$('#total').click(function() {
   List();
	$('#tblList').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
	$('#total').css('visibility','hidden');
})
$('#bRemove2').click(function() {
   
	$('#tblList').css('visibility','hidden');
	$('#total').css('visibility','visible');
	$('#form').css('visibility','hidden');
	$('#title').css('visibility','hidden');
	$('#bAdd').css('visibility','hidden');
	$('#bUpdate').css('visibility','hidden');
})
});